Deal with NULL `GC$NonLinearModel`
ianmseddy/LandR_speciesParameters pull request #42
Opened 2024-05-29 00:20 UTC by CeresBarros

Checking for class error  is not sufficient in cases where `is.null(GC$NonLinearModel)` -- I believe these come from lack of data, but perhaps need to dig further

In my fix, I check for `is.null(GC$NonLinearModel)` and also print a message differently when this is the case to avoid printing the full GC object

2024-05-29 05:22 UTC, achubaty requested changes

2024-05-29 05:22 UTC, achubaty commented on R/aNPPfunctions.R
> +    if (any("try-error" %in% c(classesNonLinear)) | is.null(classesNonLinear)) {
Needs `||` for conditional

2024-05-29 16:08 UTC, CeresBarros commented on R/aNPPfunctions.R
> +    if (any("try-error" %in% c(classesNonLinear)) | is.null(classesNonLinear)) {
Thanks! Done

2024-05-31 17:49 UTC, achubaty commented on Biomass_speciesParameters.R
> +                  "reproducible (>= 1.2.10.9001)", "SpaDES.core (>= 2.0.2.9004)",
can we set these to v 2.1.0 or higher, which are/will be the current CRAN versions?

2024-05-31 17:50 UTC, achubaty commented on Biomass_speciesParameters.R
> +                  "reproducible (>= 1.2.10.9001)", "SpaDES.core (>= 2.0.2.9004)",
(reproducible < v2.0.0 most likely won't work -- to many breaking changes going to v2)

2024-05-31 20:49 UTC, merged